# ConfigurationDB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product-service
    username: root
    password: IamPhong89
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: product-service

#JPA/Hibernate
server:
  error:
    include-message: always
  port: 8083
  
#Logging
logging:
  level:
    root: info
    org:
      springframework:
        security: INFO

#Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://@localhost:8761/eureka

#Distributed Tracing
management:
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans
    tracing:
        sampling:
            probability: 1.0